library("shiny")
library("shinyjs")
library("shinypod")

shinyUI(
  fluidPage(
    useShinyjs(),
    titlePanel("read_delim"),
    sidebarLayout(
      sidebarPanel(
        sample_delim_sb_side("delim"),
        read_delim_sb_side("data")
      ),
      mainPanel(
        sample_delim_sb_main("delim"),
        read_delim_sb_main("data")
      )
    )
  )
)
